# Generated by Django 4.0.10 on 2023-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='desc',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
