# Generated by Django 4.0.10 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_desc_alter_posts_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='posts',
            name='blog_image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
