# Generated by Django 4.0.10 on 2023-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_author_posts_author_image_posts_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author_image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
    ]
